version: "3.8"
services:
  crawler:
    build: crawler/.
    restart: always
    environment:
      - PRINT=
      - MONGO_URI=mongodb://mongo:27017/
      - JSON_PATH=

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  api:
    build: api/.
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/

  nginx:
    image: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

volumes:
  mongo_data: