name: Docker Image CI

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: ${{github.repository}}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/checkout@v2

      - name: Login to the registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_KEY }}

      - name: Build & Publish images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: keddad/torrentcrawler:latest
